version: 2

formats: 
  - htmlzip
  - pdf

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
    cmake: "3.28"    # Specify version of cmake
    doxygen: "1.9"   # Specify version of doxygen

  commands:
    - apt-get update && apt-get install -y doxygen cmake
    - pip install pybind11 sphinx breathe
    - bash compile.sh  # Compile C++ code, run Doxygen, and build docs

sphinx:
  configuration: docs/source/conf.py
