version: 2

formats: 
  - htmlzip
  - pdf

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

  apt_packages:
    - doxygen
    - cmake
    - gcc
    - g++
    - git
    - libeigen3-dev

  jobs:
    pre_create_environment:
      - echo "Command run at 'pre_create_environment' step"
      - echo "READTHEDOCS_OUTPUT=$READTHEDOCS_OUTPUT "
      - pwd; ls -lt 
      - cmake --version
      - git --version

    install:
      - pip install --upgrade pybind11 sphinx breathe numpy nbsphinx sphinx_rtd_theme
      - bash compile.sh  # Compile C++ code, run Doxygen, and build docs

sphinx:
  configuration: docs/source/conf.py
