version: 2

formats: 
  - htmlzip
  - pdf

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"

  image: "ubuntu:24.04"  # Use the Ubuntu 24.04 Docker image

  commands:
    - apt-get update && apt-get install -y doxygen cmake
    - pip install pybind11 sphinx breathe
    - bash compile.sh  # Compile C++ code, run Doxygen, and build docs

sphinx:
  configuration: docs/source/conf.py
