#ifndef MINION_H
#define MINION_H

#include "utility.h"
#include "minimizer_base.h"
#include "default_options.h"
#include "de.h"
#include "gwo_de.h"
#include "lshade.h"
#include "agsk.h"
#include "arrde.h"
#include "nlshadersp.h"
#include "nl_shade_lbc.h"
#include "j2020.h"
#include "jade.h"
#include "jso.h"
#include "lsrtde.h"
#include "rdex.h"
#include "nelder_mead.h"
#include "minimizer.h"
#include "imode.h"
#include "abc.h"
#include "dual_annealing.h"
#include "l_bfgs_b.h"
#include "l_bfgs.h"
#include "pso.h"
#include "spso2011.h"
#include "dmspso.h"
#include "lshadecnepsin.h"
#include "bipop_acmaes.h"
#include "rcmaes.h"
#include "cmaes.h"
#include "test_functions.h"

#endif // MINION_H
