name: Tests

on:
  push:
    branches:
      - main
      - "feature/*"
  pull_request:
    branches:
      - main

jobs:
  ctest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure tests (Windows)
        if: runner.os == 'Windows'
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release -DMINION_BUILD_CEC=ON -DMINION_BUILD_PYTHON=OFF -DMINION_BUILD_EXAMPLES=OFF -DMINION_BUILD_TESTS=ON

      - name: Configure tests (Non-Windows)
        if: runner.os != 'Windows'
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DMINION_BUILD_CEC=ON -DMINION_BUILD_PYTHON=OFF -DMINION_BUILD_EXAMPLES=OFF -DMINION_BUILD_TESTS=ON

      - name: Build tests
        run: cmake --build build --target minion_test --config Release

      - name: Run test binary (Windows)
        if: runner.os == 'Windows'
        run: ./build/bin/minion_test.exe

      - name: Run test binary (Non-Windows)
        if: runner.os != 'Windows'
        run: ./build/bin/minion_test
